version: "3.7"
services:

  backend:
    image: gabrielcheda/test-itau-server:latest
    ports:
      - "3000:3000"
    networks:
      - frontend

  frontend:
    image: gabrielcheda/test-itau:latest
    ports:
      - "8000:80"
    networks:
      - frontend

networks:
  frontend: